services:
  - type: web
    name: nasam
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: bash ./start.sh
    envVars:
      # Runtime basics
      - key: DJANGO_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true

      # Use Render-provided hostname for hosts/CSRF
      # RENDER_EXTERNAL_HOSTNAME is available at runtime
      - key: DJANGO_ALLOWED_HOSTS
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://${RENDER_EXTERNAL_HOSTNAME}

      # Optional email settings (uncomment and set if using Gmail SMTP)
      # - key: EMAIL_HOST_USER
      #   value: your@gmail.com
      # - key: EMAIL_HOST_PASSWORD
      #   value: app-password-here
      # - key: DEFAULT_FROM_EMAIL
      #   value: your@gmail.com

      # Optional cache tuning
      # - key: CACHE_SECONDS
      #   value: "600"

    # Optional: attach a persistent disk if you want SQLite to persist across deploys
    # Note: if you enable this, update DATABASES.NAME in core/settings.py to point to the mount path
    # disks:
    #   - name: nasam-data
    #     mountPath: /var/data
    #     sizeGB: 1
