# Generated by Django 5.0.6 on 2025-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(blank=True, help_text='Small pill text above the title', max_length=160)),
                ('title', models.CharField(help_text='Main hero heading before the accent', max_length=160)),
                ('accent', models.CharField(blank=True, help_text='Optional accent text shown with gradient', max_length=120)),
                ('lead', models.TextField(blank=True, help_text='Short paragraph under the title')),
                ('primary_cta_text', models.CharField(default='Our Services', max_length=60)),
                ('primary_cta_url', models.CharField(default='/services/', max_length=200)),
                ('secondary_cta_text', models.CharField(blank=True, default='Request a Quote', max_length=60)),
                ('secondary_cta_url', models.CharField(blank=True, default='/contact/', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Content',
            },
        ),
    ]
